# Generated by Django 3.1 on 2022-02-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryrequest',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
    ]
