# Generated by Django 3.1 on 2020-09-15 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searcher', '0002_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('select', 'select'), ('unselect', 'unselect')], default='unselect', max_length=20)),
                ('docs', models.CharField(default='', max_length=200)),
                ('min_occur', models.IntegerField(default=-1)),
                ('max_occur', models.IntegerField(default=-1)),
                ('stop_words', models.CharField(default='', max_length=500)),
                ('orig_start_year', models.CharField(default='year', max_length=12)),
                ('orig_end_year', models.CharField(default='year', max_length=12)),
                ('start_year', models.CharField(default='year', max_length=12)),
                ('end_year', models.CharField(default='year', max_length=12)),
                ('doc_number', models.CharField(default='', max_length=6)),
                ('phrases', models.CharField(default='', max_length=500)),
                ('remove_digits', models.BooleanField(default=False)),
                ('tfidf', models.BooleanField(default=False)),
                ('replacement', models.CharField(default='', max_length=1000)),
                ('level_select', models.CharField(default='', max_length=100)),
                ('para_filter_terms', models.CharField(default='', max_length=200)),
                ('passes', models.CharField(default='automatic', max_length=10)),
                ('max_hits', models.IntegerField(default=-1)),
                ('auth_s', models.CharField(default='', max_length=100)),
                ('ml_keywords', models.CharField(default='', max_length=100)),
                ('jurisdiction', models.CharField(default='', max_length=100)),
                ('journal', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='searcher.request')),
                ('database', models.CharField(default='', max_length=20)),
                ('query_str', models.CharField(default='', max_length=1000)),
            ],
            bases=('searcher.request',),
        ),
        migrations.CreateModel(
            name='VisRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='searcher.request')),
                ('model_name', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('pyLDAvis', 'pyLDAvis'), ('DFR browser', 'DFR'), ('mlmom', 'mlmom'), ('doc2vec', 'd2v'), ('word2vec', 'w2v')], max_length=20)),
                ('status', models.CharField(default='Scheduled', max_length=100)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('docfilter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='searcher.docfilter')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searcher.queryrequest')),
            ],
            bases=('searcher.request',),
        ),
    ]
