# Generated by Django 3.1 on 2022-04-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_queryrequest_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes_and_edges', models.JSONField(default=dict)),
                ('label_position_x', models.FloatField(default=0)),
                ('label_position_y', models.FloatField(default=0)),
                ('label_text', models.CharField(default='Note', max_length=500)),
                ('label_color', models.CharField(default='', max_length=20)),
                ('note_id', models.CharField(default='', max_length=50)),
                ('active_topic', models.CharField(blank=True, default='', max_length=50)),
                ('vis_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searcher.visrequest')),
            ],
        ),
    ]
