# Generated by Django 3.1 on 2020-09-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_docfilter_queryrequest_request_visrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfilter',
            name='num_topics',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='docfilter',
            name='journal',
            field=models.CharField(default='', max_length=50),
        ),
    ]
