# Generated by Django 3.1 on 2020-09-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0004_auto_20200918_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfilter',
            name='num_topics',
            field=models.CharField(default='automatic', max_length=10),
        ),
    ]
