# Generated by Django 3.1 on 2020-09-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0005_auto_20200918_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='visrequest',
            name='task_id',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
