# Generated by Django 4.0.4 on 2023-02-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0005_profile_fist_name_profile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
