# Generated by Django 3.1 on 2021-02-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0006_visrequest_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfilter',
            name='num_clusters',
            field=models.CharField(default='20', max_length=10),
        ),
        migrations.AlterField(
            model_name='docfilter',
            name='num_topics',
            field=models.CharField(default='20', max_length=10),
        ),
    ]
