ES_FIELDS = {
    'index': {
        'Covid':'covid_v4',
        'Pubmed': 'pubmed_v3',
        'PMC': 'pmc_test',
        'JSTOR': 'jstor',
        '': '_care_note',
        '_encounter': '_care_encounter',
        'CaseLaw': 'case_law',
        'Archaeology': 'archaeology',
        'Latin': 'latin',
        'Ehealth': 'alzheimer_threads',
        'TCP': 'tcp',
        'ACJ': 'ac_justice',
        'AA': 'anesthesiology',
        'CaseLaw_v2': 'case_law_v2',
        '' : '_notes',
        'TED' : 'ted_talks',
        'Pulmonary' : 'pulmonary_notes',
        'Ehealth_Threads': 'alzheimer_threads', 
        'Cannabis_News':'cannabis',
        'NPO_taxforms':'npo_990forms',
        'OHNPO_taxforms': 'ohio_npo_essential',
        'Pubmed_COI': 'coi_statements',
        'Reddit' : 'parenting_subreddit', 
        'SAA_Abstracts': 'arch_abstracts',
        '': ''
    },
    'id': {
        'Covid':'paper_id',
        'Pubmed': 'PMID',
        'PMC': 'PMCID',
        'JSTOR': 'JSTOR_ID',
        '': 'NOTE_ID',
        '_encounter': 'NOTE_ID',
        'CaseLaw': 'CaseID',
        'Archaeology': 'ArticleID',
        'Latin': 'ArticleID',
        'Ehealth': 'id',
        'TCP': 'TCPID',
        'ACJ': 'Pid',
        'AA': 'SID',
        'CaseLaw_v2': 'CaseID',
        '' : 'NoteID',
        'TED' : 'Talk_ID',
        'Pulmonary': 'NoteID',
        'Ehealth_Threads': 'id',
        'Cannabis_News':'id', 
        'NPO_taxforms':'id',
        'OHNPO_taxforms':'id',
        'Pubmed_COI': 'pmid',
        'Reddit' : 'ID',
        'SAA_Abstracts': 'id', 
        '': 'id'
    },
    'abstract': {
        'Covid':'abstract',
        'Pubmed': 'AbstractText',
        'PMC': 'Abstract',
        'JSTOR': 'FullText',
        'CaseLaw': 'FullText',
        'Archaeology': 'FullText',
        'Latin': 'FullText',
        'Ehealth': 'text',
        'TCP': 'FullText',
        'ACJ': 'FullText',
        'AA': 'Abstract',
        'CaseLaw_v2': 'FullText',
        '' : 'FullText',
        'TED' : 'FullText',
        'Pulmonary': 'FullText',
        'Ehealth_Threads': 'text', 
        'Cannabis_News':'text', 
        'NPO_taxforms':'text',
        'OHNPO_taxforms': 'text', 
        'Pubmed_COI': 'coi',
        'Reddit' : 'FullText',
        'SAA_Abstracts': 'text',
        '': 'text'
    },
    'full_text': {
        'Covid':'fullText',
        'Pubmed': 'AbstractText',
        'PMC': 'FullText',
        'JSTOR': 'FullText',
        '': 'HPI_SOCIAL_HISTORY',
        '_encounter': 'HPI_SOCIAL_HISTORY',
        'CaseLaw': 'FullText',
        'Archaeology': 'FullText',
        'Latin': 'FullText',
        'Ehealth': 'text',
        'TCP': 'FullText',
        'ACJ': 'FullText',
        'AA': 'Abstract',
        'CaseLaw_v2': 'FullText',
        '' : 'FullText',
        'TED' : 'FullText',
        'Pulmonary': 'FullText',
        'Ehealth_Threads': 'text',
        'Cannabis_News':'text', 
        'NPO_taxforms':'text',
        'OHNPO_taxforms':'text',
        'Pubmed_COI': 'coi',
        'Reddit' : 'FullText',
        'SAA_Abstracts': 'text', 
        '': 'text'
    },
    'doc_title' :
        {
             'Covid': 'title',
        'Pubmed': 'ArticleTitle',
        'PMC': 'ArticleTitle',
        'JSTOR': 'ArticleTitle',
        '': 'PAT_ID',
        '_encounter': 'PAT_ID',
        'CaseLaw': 'Name',
        'Archaeology': 'ArticleTitle',
        'Latin': 'ArticleTitle',
        'Ehealth': 'TopicID',
        'TCP': 'ArticleTitle',
        'ACJ': 'ArticleTitle',
        'AA': 'ArticleTitle',
        'CaseLaw_v2': 'Name',
        '' : 'NoteID',
        'TED' : 'Name',
        'Pulmonary': 'NoteID',
        'Cannabis_News': 'link', 
        'Pubmed_COI': 'article',
        'Reddit' : 'ID',
        'NPO_taxforms': 'id',
        'OHNPO_taxforms': 'id',
        'SAA_Abstracts': 'id', 
        '': 'title'
        },
    'author' :
        {
            'Covid': 'authors',
        'PMC': 'ArticleTitle',
        'JSTOR': 'Authors',
        'TCP': 'Authors',
        'AA': 'Authors',
        'TED' : 'Speaker_1',
        'Pubmed_COI': 'authors',
        'Reddit' : 'ID',
        'Cannabis_News': 'title', 
        },
    'date': {
        'Covid':'date',
        'Pubmed': 'ReleaseDate',
        'PMC': 'ReleaseDate',
        'JSTOR': 'ReleaseDate',
        '': 'TODO',
        'CaseLaw': 'DecisionDate',
        'Archaeology': 'ReleaseDate',
        'Latin': 'No_date',
        'Ehealth': 'date',
        'TCP': 'PubDate',
        'ACJ': 'PubDate',
        'AA': 'Date',
        'CaseLaw_v2': 'DecisionDate',
        '' : 'NoteDate',
        'TED' : 'PubDate',
        'Pulmonary': 'NoteDate',
        'Ehealth_Threads': 'date', 
        'Cannabis_News':'date', 
        'NPO_taxforms':'date',
        'OHNPO_taxforms': 'date',
        'Cannabis_News':'date',
        'Pubmed_COI': 'pub_year',
        'Reddit' : 'Date',
        'SAA_Abstracts': 'date', 
        '': 'date'
    },
    'doc_type': {
        '': 'note',
        '_encounter': 'note'
    },
    'info': {
        'Covid':['paper_id','bib_entries','authors'],
        'Pubmed': ['PMID', 'ReleaseDate'],
        'PMC': ['ID', 'Journal', 'Pub Date', 'Authors'],
        'JSTOR': ['ID', 'Journal', 'Pub Date', 'Authors'],
        '': ['TODO'],
        'CaseLaw': ['ID', 'Date'],
        'Ehealth': ['id', 'date'],
        'TCP': ['ID', 'PubDate', 'Authors'],
        'ACJ': ['ID', 'PubDate'],
        'CaseLaw_v2': ['ID', 'Date'],
        '' : ['NoteID','NoteDate'],
        'TED' : ['Talk_ID', 'PubDate'],
        'Pulmonary':['NoteID', 'NoteDate'],
        'Ehealth_Threads': ['id', 'date'], 
        'Cannabis_News':['id', 'date'],
        'NPO_taxforms':['id', 'date'],
        'OHNPO_taxforms':['id', 'date'],
        'Cannabis_News':['id', 'date'], 
        'Pubmed_COI': ['pmid','journal', 'authors'],
        'Reddit' : ['ID', 'Date'],
        'SAA_Abstracts': ['id', 'date'], 
        '': ['id', 'date']
    }
}
MAX_NUM_DOC_VIS = {
    'Covid': 144000,
    'Pubmed': 20000,
    'PMC': 20000,
    'JSTOR': 4000,
    '': 10000,
    'CaseLaw': 20000,
    'Archaeology': 5000,
    'Latin': 20000,
    'Ehealth': 20000,
    'TCP': 1500,
    'ACJ': 20000,
    'searchpage' : 144000,
    'CaseLaw_v2' : 20000,
    'AA' : 23000,
    '' : 20000,
    'TED' : 20000,
    'Pulmonary': 20000,
    'Ehealth_Threads': 20000,
    'Cannabis_News': 15000, 
    'NPO_taxforms': 20000,
    'OHNPO_taxforms': 10000,
    'Cannabis_News': 14000,
    'Pubmed_COI': 20000,
    'Reddit' : 50000,
    'SAA_Abstracts': 20000, 
    '': 4000
}
